exclusions = [
    "bitcoin*",
    "solana*",
    "ethereum*",

    "sentry*",

    "curl_sys",
    "neon_sys",
    "sentry-contrib-native-sys",
    "rusty_v8",
    "rustc-serialize",
]

additions = [
    # Crates that the compiler recommends
    # rg 'https://crates.io/crates/[a-z_-]+' --glob '*.stderr' --only-matching --no-line-number --no-filename | sort | uniq | cut -d '/' -f 5
    "async-trait",
    "async-recursion",

    "globset",
    "flatbuffers",
    "protobuf",
    "scan_fmt",
    "permutator",
    "text_io",
    "md5",
    "indicatif",
    "permutator",
    "structopt",
    "structopt-derive",

    "panamax",
    "lsd",
    "ripgrep",
    "procs",
    "dua-cli",
    "bottom",
    "dust",
    "cross",
    "tui",
    "cargo-edit",
    "cargo",
]
