exclusions = [
    "bitcoin*",
    "solana*",
    "ethereum*",

    "sentry*",

    "curl_sys",
    "neon_sys",
    "sentry-contrib-native-sys",
    "rusty_v8",
    "rustc-serialize",

    "vsdb*",
    "btm",
    "js-sys*",
    "jni",
    "gloo*",
]

commands = [
    "panamax",
    "lsd",
    "ripgrep",
    "procs",
    "dua-cli",
    "bottom",
    "dust",
    "cargo-edit",
    "cargo",
    "kmon",
]

additions = [
    "async-trait",
    "async-recursion",

    "globset",
    "flatbuffers",
    "protobuf",
    "scan_fmt",
    "permutator",
    "text_io",
    "md5",
    "indicatif",
    "permutator",
    "structopt",
    "structopt-derive",
    "tui",
    "redis",
    "rusqlite",

    "xml-rs",
    "heck",

    "globset",
    "cargo",
    "reqwest",
    "indicatif",
    "structopt",
    "toml",
    "serde",
    "console",
    "log",
    "env_logger",
    "sha2",
    "url",
    "glob",
    "git2",
    "serde_json",
    "thiserror",
    "tokio",
    "warp",
    "askama",
    "askama_warp",
    "include_dir",
    "bytes",
    "tokio-stream",
    "tokio-util",
    "futures-util",
    "futures",
]
