top-crates = 200

cookbook = true

categories = [
    { "command-line-utilities" = 0 },
    { "development-tools" = 10 },
    { "development-tools::procedural-macro-helpers" = 0 },
    { "development-tools::cargo-plugins" = 0 },
    { "development-tools::testing" = 0 },
    { "development-tools::profiling" = 0 },
    { "development-tools::ffi" = 0 },
    { "development-tools::debugging" = 0 },
    { "development-tools::build-utils" = 0 },
    { "web-programming" = 20 },
    { "web-programming::http-client" = 10 },
    { "web-programming::websocket" = 10 },
    { "web-programming::http-server" = 10 },
    { "api-bindings" = 20 },
    { "network-programming" = 20 },
    { "data-structures" = 20 },
    { "cryptography" = 20 },
    { "asynchronous" = 20 },
    { "embedded" = 5 },
    { "algorithms" = 0 },
    { "mathematics" = 0 },
    { "science" = 20 },
    { "filesystem" = 10 },
]

exclusions = [
    "bitcoin*",
    "solana*",
    "ethereum*",
    "sentry*",

    "curl_sys",
    "neon_sys",
    "sentry-contrib-native-sys",
    "rusty_v8",
    "rustc-serialize",

    "vsdb*",
    "btm",
]

commands = [
    "ripgrep", # https://github.com/BurntSushi/ripgrep
    "bat",     # https://github.com/sharkdp/bat
    "lsd",     # https://github.com/Peltoche/lsd
    "bottom",  # https://github.com/ClementTsang/bottom
    "procs",   # https://github.com/dalance/procs
    "dua-cli", # https://github.com/Byron/dua-cli

    # https://crates.io/keywords/cargo-subcommand
    "cargo-edit",
    "cargo-local-registry",
    "cargo-valgrind",
    # "cargo-tarpaulin",    # code coverage, only on Linux x86_64
    # "flamegraph",         # https://github.com/flamegraph-rs/flamegraph
    # "cargo-audit",        # https://github.com/rustsec/rustsec
]

additions = [
    "rayon",
    "globset",
    "flatbuffers",
    "protobuf",
    "scan_fmt",
    "permutator",
    "text_io",
    "md5",
    "indicatif",
    "permutator",
    "structopt",
    "structopt-derive",
    "tui",
    "redis",
    "rusqlite",
    "xml-rs",
    "heck",
    "reqwest",
    "toml",
    "serde",
    "console",
    "log",
    "env_logger",
    "sha2",
    "url",
    "glob",
    "git2",
    "serde_json",
    "thiserror",
    "tokio",
    "warp",
    "askama",
    "askama_warp",
    "include_dir",
    "bytes",
    "tokio-stream",
    "tokio-util",
    "futures-util",
    "futures",
]
